[package]
name = "json_parse"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.2", features = ["blocking", "json"]}
serde_json = "1.0.64"
regex = "1.4.4"
termion = "1.5.6"
